apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-jy2y
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0036-tenant/tkrw-pr712-0075-0036-app/devfile-sample-jy2y@sha256:d60289f98fb07ee7a28902c62702104aaa9100c3a256f5aa2783ae54ac3f418a
        name: my-nodejs
        resources: {}
status: {}
